# Generated by Django 3.2.7 on 2024-08-26 00:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название торта')),
                ('image', models.CharField(max_length=50, verbose_name='Картинка торта')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID покупателя')),
                ('tg_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя покупателя в Телеграме')),
                ('first_name', models.CharField(blank=True, max_length=56, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('GDPR_status', models.BooleanField(default=False, null=True)),
                ('home_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Домашний адрес')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Product_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bake_bot.product')),
            ],
            options={
                'verbose_name': 'Свойства Продукта',
                'verbose_name_plural': 'Свойства Продуктов',
            },
        ),
        migrations.CreateModel(
            name='Product_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=256, verbose_name='Название параметра')),
                ('parameter_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('product_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bake_bot.product_properties', verbose_name='Свойства Продукта')),
            ],
            options={
                'verbose_name': 'Параметры продукта',
                'verbose_name_plural': 'Параметры продуктов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя Покупателя')),
                ('customer_chat_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat ID Покупателя')),
                ('order_details', jsonfield.fields.JSONField(default='Пока нет ничего', verbose_name='Детали заказа')),
                ('order_price', models.PositiveIntegerField(verbose_name='Цена заказа')),
                ('order_status', models.CharField(choices=[('Заявка обрабатывается', 'Заявка обрабатывается'), ('Готовим ваш торт', 'Готовим ваш торт'), ('Продукт в пути', 'Продукт в пути'), ('Продукт у вас', 'Продукт у вас')], default='Заявка обрабатывается', max_length=256, verbose_name='Статус заказа')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарии')),
                ('delivery_address', models.CharField(default=' ', max_length=256, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('order_type', models.CharField(choices=[('Собрать свой торт', 'Собрать свой торт'), ('Заказать торт', 'Заказать торт')], default='Заказать торт', max_length=17, verbose_name='Тип заказа')),
                ('cake_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Bake_bot.cake', verbose_name='Название торта')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
